blockExoticSubdeps: true
strictDepBuilds: true
minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - typst-wasm
  - "@typst-wasm/engine-wasm"
  - "@typst-wasm/vite-plugin-typst"
  - "@typst-wasm/fonts"
trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 43200
allowBuilds:
  esbuild: true
  sharp: true
  workerd: true
patchedDependencies:
  "@myriaddreamin/vite-plugin-typst": patches/@myriaddreamin__vite-plugin-typst.patch
